### ISSUE TITLE
I had to add an event subscription to get it to work

### ISSUE THREAD

**Issue by thinkmonkeys** [normandmickey/MrsStax#4]
![Screenshot 2023-03-29 at 11 24 24](https://user-images.githubusercontent.com/4026226/228505328-e978c742-6469-4862-bd60-6745fc9d4ce7.png)

**Comment by thinkmonkeys** [comment]
You should add to the README.
Nice work btw, working well now

**Comment by normandmickey** [comment]
Thanks!  I will update the instructions soon.  OpenAI and Langchain are rapidly evolving projects. I plan to refactor this to use "gpt-3.5-turbo" (ChatGPT) which is about 15x less expensive per token than Davinci.

**Comment by normandmickey** [comment]
Added "Subscribe to Bot Events" instructions to README.md
