### ISSUE TITLE
Rate limit error

### ISSUE THREAD

**Issue by ciquezada** [normandmickey/MrsStax#5]
A have an rate limit error when ingesting:
'errors': {'error': [{'message': 'update vector: failed with status: 429%!!(MISSING)(EXTRA string=Rate limit reached for default-global-with-image-limits in organization org-m63Ws2YtNTuk2VHj5iRVQ7kp on requests per min. Limit: 60 / min. Please try again in 1s. Contact [support@openai.com](mailto:support@openai.com) if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.)'}]}}

**Comment by normandmickey** [comment]
If you just signed up for the OpenAI Api Key you are subject to the following rate limits. 
It looks like the limits will be lifted after 48 hours.
https://platform.openai.com/docs/guides/rate-limits/overview

![image](https://user-images.githubusercontent.com/2455566/228691623-86386299-9fa8-4990-bfeb-5cd7252fc063.png)
